config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#new'

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  resources :tasks

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'sign_up' => 'users#new'
end

app/models/task.rb
class Task < ActiveRecord::Base

scope :incomplete, -> { where(completed: false) }

end

app/models/user.rb
class User < ActiveRecord::Base

	validates :email, presence: true

	has_secure_password
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # respond_to :html, :js
	# before_filter :ensure_logged_in
	
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def ensure_logged_in
    if session[:user_id].nil?
      redirect_to login_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_filter :ensure_logged_in, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by_email(params[:email]).try(:authenticate, params[:password])
    if user
      session[:user_id] = user.id
      redirect_to users_path, notice: "You are logged in!"
    else
      flash.now.alert = "Invalid email or password. Please try again."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: "You have logged out!"
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	# before_action :load



	# .button= link_to 'Mark Complete', complete_task_path(@task/task - if in a do |task| ), method: :patch    # Looks for complete method

	# def complete
	# 	@task = Task.find(params[:id])
	# 	@task.update_attributes(complete: true)
	#   redirect_to ??
	# end

	# resources: tasks do
	# 	memeber do
	# 		patch :complete
	# 	end
	# end

	# def load
	# 	@tasks = Task.all
	# 	@task = Task.new
	# end



	def index
		 @tasks = Task.all
		 @task = Task.new
		# @tasks = Task.incomplete
	end

  def create
    # @task = Task.new(task_params)
    @task = Task.new(task_params)
    @tasks = Task.all
    @task.save
    respond_to do |format|
    	format.js {}
    	format.html { redirect_to :index }
    end
    # save_task
    # @tasks = Task.all
    # if @task.save
   	# 	render :hide_form
   	# end
    # if @task.save
    	# redirect_to tasks_path
    # end
  end

  def destroy
  	@task = Task.find(params[:id])
  	@task.destroy
  	@tasks = Task.all
  end

  def edit
  	@task = Task.find(params[:id])
  	render :show_form
  end

	def update
		# @task = Task.find(params[:id])
		# if @task.update_attributes(task_params)
		# 	respond_to do |format|
		# 		format.js
		# 		format.html { redirect_to tasks_path }
		# 	end
		# else
		# 	respond_to do |format|
		# 		format.js { render plain: "0" } 
		# 		format.html { redirect_to tasks_path, notice: "Update failed." }
		# 	end
		# end
		@task = Task.find(params[:id])
		@task.update_attributes(task_params)
		@tasks = Task.all
		respond_to do |format|
    	format.js {}
    	format.html { redirect_to :index }
    end
		# render :hide_form
		#save_task
	end

	private

	def save_task
		if @task.save 
			# @tasks = Task.all 
			respond_to do |format|
				format.js{ render :hide_form }
			end
		else
			render :show_form
		end
	end

	def task_params
		params.require(:task).permit(:title, :completed)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # before_action :ensure_logged_in, only: [:new, :create, :destroy, :delete]


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    # @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        # Tells UserMailer to send a welcome email
        UserMailer.welcome_email(@user).deliver

        # format.html { redirect_to @user, notice: 'User was successfully created.' }
        # format.json { render :show, status: :created, location: @user }

        format.html { redirect_to(@user, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :login, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "User Auth & Email App"
		page_title.empty? ?  base_title : "#{base_title} | #{page_title}"
	end

	def format_date(date)

    if !date.nil?
      date.strftime("%B %d, %Y")
    else
      "No record"
    end
  end
  
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield :title)
    = favicon_link_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      .row
        .navbar.navbar-inverse.navbar-fixed-top
          .navbar-header
            %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", type: "button"}
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
          = link_to "Users Auth App", users_path, :class => "navbar-brand"
          .navbar-collapse.collapse.navbar-responsive-collapse
            %ul.nav.navbar-nav
              %li= link_to "Home", users_path
            %ul.nav.navbar-nav.navbar-right
              %li= link_to "Logout", logout_path, :data => { confirm: "Logout?"}  
    %br             
    = yield

app/views/tasks/_form.html.haml
.modal-body
	= f.text_field :title, class: "new-input"
.modal-footer
	= f.submit 'Save', :id => 'save', class: 'btn btn-primary'

app/views/tasks/_task.html.haml
%li
	= task.title
	= check_box_tag "completed", "1", task.completed, data: { "task-id" => task.id }
	
	= link_to 'x', task_path(task), remote: true, method: :delete, data: {confirm: "Are you sure you want to delete this task?"}
	= button_tag(type: "button", class: "btn btn-primary shit", "task-id" => task.id) do
		= content_tag(:strong, "Edit task")
	.modal.fade.update-modal{id: "edit-task-#{task.id}"}
		.modal-header
			%h1 Edit Task
		= form_for(task, remote: true, id: "edit-form", method: :put) do |f|
			= render "form", f: f

app/views/tasks/_task_form.html.haml
.modal-header
	%h1 Tasks
= form_for(Task.new, class: 'clearfix', remote: true) do |f|
	.modal-body
		= f.text_field :title
	.modal-footer
		= f.submit 'Save', :id => 'save', class: 'btn btn-primary'

app/views/tasks/_task_list.html.haml
.container
/ - if tasks.empty?
/ 	%span.text-warning There are no tasks!
/ - else
/ 	%br
/ 	%h3 Uncompleted Tasks
/ 	%table.table.table-hover.table-bordered
/ 		%thead
/ 			%tr
/ 				%th Title
/ 				%th Completed?
/ 		%tbody
/ 			- tasks.each do |task|
/ 				%tr
/ 					%td= task.title
/ 					%td= check_box_tag "completed", "1", task.completed, data: { "task-id" => task.id }
/ 					%td
/ 						= link_to 'x', task_path(task), remote: true, method: :delete, data: {confirm: "Are you sure you want to delete this task?"}
/ 						= button_tag(type: "button", class: "btn btn-primary shit", "task-id" => task.id) do
/ 							= content_tag(:strong, "Edit task")
/ 					.modal.fade{id: "taskmodal#{task.id}"}
/ 						= render partial: "task_form", locals: {task: task, tasks: tasks}

%ul{id: "tasks"}
	- tasks.each do |task|
		= render partial: "task", locals: { task: task }

app/views/tasks/create.js.erb
$('<%= escape_javascript(render @task) %>').appendTo("#tasks");
$('#new-task-modal').modal('hide');

app/views/tasks/destroy.js.erb
$('#task-list').html('<%= j(render partial: 'task_list', locals: {tasks: @tasks})%>');

app/views/tasks/hide_form.js.erb
console.log('hide modal')
$('#task-list').html('<%= j(render partial: 'task_list', locals: {task: @task}) %>');
$('#modal').modal('toggle');

app/views/tasks/index.html.haml
/ .container
/ 	.row
/ 		.col-md-3
/ 		.col-md-6
/ 			= form_for(Task.new, remote: true, id: "new-form") do |f|
/ 				= f.text_field :title, class: "new-input"
/ 				= f.submit 'Save', :id => 'save', class: 'btn btn-primary'
/ 		.col-md-3
/ 	%br

#task-list.container 
	= render partial: 'tasks/task_list', locals: {tasks: @tasks}

%br
//= button_to 'New Task', new_task_path

= button_tag(type: "button", class: "btn btn-primary", id: "new-task-btn") do
	= content_tag(:strong, "New task")
.modal.fade{id: "new-task-modal"}
	.modal-header
		%h1 Tasks
	= form_for(Task.new, remote: true, id: "new-form") do |f|
		= render "form", f: f

app/views/tasks/new.html.haml
.container
	.row
		%h1 New Task

		= render 'form'

		= link_to 'Back', tasks_path

app/views/tasks/show_form.js.erb
$('#modal').html('<%= j(render partial: 'task_form', locals: {task: @task}) %>');
$('#modal').modal('toggle');
console.log('show modal')

app/views/tasks/update.js.erb
$('.update-modal').modal('toggle');
//$('<%= escape_javascript(render @task) %>').appendTo("#tasks");
$('#task-list').html('<%= j(render partial: 'task_list', locals: {tasks: @tasks})%>');

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label 'Confirm Password'
    = f.password_field :password_confirmation
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
.container
  .row
  .headerClass
    %h1 Registered users

  %table
    %tr
      %th Name
      %th Email
      %th
      %th
      %th

    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br

  = button_to 'New User', new_user_path, method: "get", :class => "btn btn-xs btn-success"

:javascript
  $(".headerClass").on('click', function() {
    $(this).addClass("anotherClass");
  });

app/views/users/new.html.haml
.container
	.row
		%h1 New user

		= render 'form'

		= link_to 'Back', users_path
	.row
		%br
		%p
			%img#imgClickAndChange{:alt => "", :onclick => "changeImage()", :src => "http://www.pointreyesseashore.com/blog/wp-content/uploads/beach-small1.JPG", :style => "height: 185px; width: 298px"}

:javascript
	function changeImage() {
		if (document.getElementById("imgClickAndChange").src == "http://www.pointreyesseashore.com/blog/wp-content/uploads/beach-small1.JPG") 
		{
			document.getElementById("imgClickAndChange").src = "http://ultrafithealth.com/wp-content/uploads/2014/01/myrtle-beach-small.jpg";
		}
		else 
		{
			document.getElementById("imgClickAndChange").src = "http://www.pointreyesseashore.com/blog/wp-content/uploads/beach-small1.JPG";
		}
	}

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email
%p
  %b Login:
  = @user.login

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path